### ISSUE TITLE
Implement ring crypto backend

### ISSUE THREAD

**Issue by eoger** [mozilla/rust-ece#9]
I believe https://github.com/briansmith/ring/pull/739 should unblock us.

**Comment by rfk** [comment]
Since we're now using a custom NSS backend for this in https://github.com/mozilla/application-services, I don't think we have any incentive to add a separate `ring` backend ourselves. I'd be happy to review such a thing if it were important to other contributors, but I'm going to close the issue here since we're not likely to work on it in future.
